'use strict';
const PROJECT='https://gqbekbrxftmfpgnkqodo.supabase.co';
const $=s=>document.querySelector(s);let config=null,session=null,sites=[],records=[];
const status=(text,bad=false)=>{const n=$('#adminStatus');n.textContent=text;n.className=`notice${bad?' warning':''}`};
async function request(path,{method='GET',body,auth=true}={}){if(!config)throw Error('Backend is not configured.');const headers={'apikey':config.publishableKey,'Content-Type':'application/json'};if(auth){if(!session?.access_token)throw Error('Sign in required.');headers.Authorization=`Bearer ${session.access_token}`;}const r=await fetch(`${PROJECT}${path}`,{method,headers,body:body?JSON.stringify(body):undefined,cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer'});const value=await r.json().catch(()=>({}));if(!r.ok)throw Error(value.message||value.error_description||value.error||'Request failed.');return value}
async function rpc(name,args){return request(`/rest/v1/rpc/${name}`,{method:'POST',body:args})}
function clearSession(){session=null;records=[];$('#workspace').hidden=true;$('#signInForm').hidden=!config;$('#signInForm').reset();status(config?'Signed out.':'Private administration is not configured.',!config)}
function entitySpec(){const e=$('#entity').value;if(e==='listings')return {label:'name',extra:'public_url',statuses:['draft','review','published','archived']};if(e==='content_items')return {label:'title',extra:'slug',statuses:['draft','review','published','archived']};return {label:'title',extra:'due_at',statuses:['open','in_progress','blocked','done','cancelled']}}
function resetForm(){const f=$('#recordForm');f.reset();f.id.value='';syncForm()}
function syncForm(){const s=entitySpec(),f=$('#recordForm');f.status.replaceChildren(...s.statuses.map(v=>new Option(v.replaceAll('_',' '),v)));$('#priorityWrap').hidden=$('#entity').value!=='tasks'}
function render(){const box=$('#records');box.replaceChildren(...records.map(row=>{const card=document.createElement('article');card.className='panel';const title=document.createElement('h2');title.textContent=row.name||row.title;const meta=document.createElement('p');meta.className='source-line';meta.textContent=`${row.status} · updated ${new Date(row.updated_at).toLocaleString('en-AU')}`;const edit=document.createElement('button');edit.className='button secondary';edit.type='button';edit.textContent='Edit';edit.onclick=()=>{const f=$('#recordForm'),s=entitySpec();f.id.value=row.id;f.site_id.value=row.site_id;f.label.value=row[s.label]||'';f.extra.value=row[s.extra]||'';f.status.value=row.status;f.priority.value=row.priority||'normal';scrollTo({top:f.offsetTop,behavior:'smooth'})};card.append(title,meta,edit);return card}));if(!records.length)box.append(Object.assign(document.createElement('p'),{textContent:'No records yet.'}))}
async function load(){sites=await rpc('admin_list',{entity:'sites'});const sel=$('#recordForm [name=site_id]');sel.replaceChildren(...sites.map(s=>new Option(s.public_site_key,s.id)));records=await rpc('admin_list',{entity:$('#entity').value});render();status('Private workspace connected.')}
addEventListener('DOMContentLoaded',async()=>{try{const r=await fetch('/api/config',{cache:'no-store',credentials:'same-origin'});if(!r.ok)throw Error();config=await r.json();if(config.supabaseUrl!==PROJECT||!config.publishableKey.startsWith('sb_publishable_'))throw Error();$('#signInForm').hidden=false;status('Secure backend available. Sign in to continue.')}catch{status('Private administration is not configured. Public dashboard remains read-only.',true)}syncForm()});
$('#signInForm').addEventListener('submit',async e=>{e.preventDefault();status('Signing in…');try{const f=new FormData(e.currentTarget);session=await request('/auth/v1/token?grant_type=password',{method:'POST',auth:false,body:{email:f.get('email'),password:f.get('password')}});e.currentTarget.reset();e.currentTarget.hidden=true;$('#workspace').hidden=false;await load()}catch(err){session=null;status(err.message,true)}});
$('#signOut').onclick=async()=>{try{if(session)await request('/auth/v1/logout',{method:'POST'})}catch{}clearSession()};
$('#entity').onchange=async()=>{resetForm();try{records=await rpc('admin_list',{entity:$('#entity').value});render()}catch(err){status(err.message,true)}};
$('#clearRecord').onclick=resetForm;
$('#recordForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,s=entitySpec(),record={id:f.id.value||undefined,site_id:f.site_id.value,status:f.status.value,[s.label]:f.label.value.trim()};if(f.extra.value.trim())record[s.extra]=f.extra.value.trim();if($('#entity').value==='tasks')record.priority=f.priority.value;try{await rpc('admin_upsert',{entity:$('#entity').value,record});resetForm();records=await rpc('admin_list',{entity:$('#entity').value});render();status('Saved and audited.')}catch(err){status(err.message,true)}});
addEventListener('pagehide',()=>{session=null});
