'use strict';
const $=selector=>document.querySelector(selector);const auth=window.DCCAuth;let configReady=false,sites=[],records=[];
const status=(text,bad=false)=>{const node=$('#adminStatus');node.textContent=text;node.className=`notice${bad?' warning':''}`};
function hidePrivateViews(){$('#workspace').hidden=true;$('#pendingApproval').hidden=true}
function showSignedOut(message='Signed out.'){records=[];sites=[];hidePrivateViews();$('#signInForm').hidden=!configReady;$('#signInForm').reset();status(configReady?message:'Private administration is not configured.',!configReady)}
function showPending(){const claims=auth.validateAccessToken(auth.getSession().access_token);hidePrivateViews();$('#signInForm').hidden=true;$('#approvalCode').textContent=auth.approvalCode();$('#approvalUserId').textContent=claims.sub;$('#pendingApproval').hidden=false;status('This device is authenticated but is still awaiting private administrator approval.')}
function isPending(error){return error?.status===401||error?.status===403||/insufficient_role|permission denied|not authorised|not authorized/i.test(error?.message||'')}
function entitySpec(){const entity=$('#entity').value;if(entity==='listings')return {label:'name',extra:'public_url',statuses:['draft','review','published','archived']};if(entity==='content_items')return {label:'title',extra:'slug',statuses:['draft','review','published','archived']};return {label:'title',extra:'due_at',statuses:['open','in_progress','blocked','done','cancelled']}}
function resetForm(){const form=$('#recordForm');form.reset();form.id.value='';syncForm()}
function syncForm(){const spec=entitySpec(),form=$('#recordForm');form.status.replaceChildren(...spec.statuses.map(value=>new Option(value.replaceAll('_',' '),value)));$('#priorityWrap').hidden=$('#entity').value!=='tasks'}
function render(){const box=$('#records');box.replaceChildren(...records.map(row=>{const card=document.createElement('article');card.className='panel';const title=document.createElement('h2');title.textContent=row.name||row.title;const meta=document.createElement('p');meta.className='source-line';meta.textContent=`${row.status} · updated ${new Date(row.updated_at).toLocaleString('en-AU')}`;const edit=document.createElement('button');edit.className='button secondary';edit.type='button';edit.textContent='Edit';edit.onclick=()=>{const form=$('#recordForm'),spec=entitySpec();form.id.value=row.id;form.site_id.value=row.site_id;form.label.value=row[spec.label]||'';form.extra.value=row[spec.extra]||'';form.status.value=row.status;form.priority.value=row.priority||'normal';scrollTo({top:form.offsetTop,behavior:'smooth'})};card.append(title,meta,edit);return card}));if(!records.length)box.append(Object.assign(document.createElement('p'),{textContent:'No records yet.'}))}
async function load(){sites=await auth.rpc('admin_list',{entity:'sites'});const select=$('#recordForm [name=site_id]');select.replaceChildren(...sites.map(site=>new Option(site.public_site_key,site.id)));records=await auth.rpc('admin_list',{entity:$('#entity').value});render();hidePrivateViews();$('#signInForm').hidden=true;$('#workspace').hidden=false;status('Private workspace connected on this trusted device.')}
async function openOrPending(){try{await load();return true}catch(error){if(isPending(error)){showPending();return false}throw error}}
async function completeMagicLink(){const params=auth.authParams();if(!params.tokenHash&&!params.accessToken&&!params.url.searchParams.get('error')&&!new URLSearchParams(params.url.hash.slice(1)).get('error'))return false;try{status('Verifying sign-in link…');if(params.type&&!['magiclink','email'].includes(params.type))throw Error('Sign-in link type was refused.');if(!auth.acceptRedirectSession(params)){if(!params.tokenHash||!params.type)throw Error('Sign-in link could not be verified.');const value=await auth.request(`/auth/v1/verify?type=${encodeURIComponent(params.type)}`,{method:'POST',auth:false,body:{token_hash:params.tokenHash}});if(!value?.access_token||!value?.refresh_token)throw Error('Sign-in link could not be verified.');auth.validateAccessToken(value.access_token);auth.setSession(value)}auth.scrubAuthParams(params.url);await openOrPending();return true}catch(error){auth.clearSession();auth.scrubAuthParams(params.url);status(error.message||'Sign-in link could not be verified.',true);return true}}
addEventListener('DOMContentLoaded',async()=>{try{await auth.loadConfig();configReady=true;syncForm();if(await completeMagicLink())return;if(auth.hasStoredSession()){try{await auth.restoreSession();await openOrPending();return}catch{auth.clearSession()}}$('#signInForm').hidden=false;status('Secure backend available. Activate this device, or use the authorised email-link fallback.')}catch{configReady=false;auth.clearSession();status('Private administration is not configured. Public dashboard remains read-only.',true)}syncForm()});
auth.onSessionExpired(()=>showSignedOut('Your saved sign-in expired or was revoked. Activate this device again.'));
$('#activateDevice').onclick=async()=>{status('Creating a private device identity…');try{const value=await auth.request('/auth/v1/signup',{method:'POST',auth:false,body:{}});if(!value?.access_token||!value?.refresh_token)throw Error('Device activation did not return a session.');auth.validateAccessToken(value.access_token);auth.setSession(value);showPending()}catch(error){auth.clearSession();status(error.message||'Device activation failed.',true)}};
$('#signInForm').addEventListener('submit',async event=>{event.preventDefault();status('Sending sign-in link…');try{const form=new FormData(event.currentTarget);await auth.request('/auth/v1/otp',{method:'POST',auth:false,body:{email:form.get('email'),should_create_user:false,email_redirect_to:auth.exactAdminRedirect()}});event.currentTarget.reset();status('If that address is authorised, a one-use device activation link has been sent.')}catch(error){event.currentTarget.reset();status(error.message,true)}});
$('#retryApproval').onclick=async()=>{status('Checking approval…');try{await auth.refreshSession();await openOrPending()}catch(error){status(error.message,true)}};
async function signOut(message){try{if(auth.getSession())await auth.request('/auth/v1/logout?scope=local',{method:'POST'})}catch{}finally{auth.clearSession();showSignedOut(message)}}
$('#cancelActivation').onclick=()=>signOut('Device activation cleared.');$('#signOut').onclick=()=>signOut('Signed out and the saved device session was revoked.');
$('#entity').onchange=async()=>{resetForm();try{records=await auth.rpc('admin_list',{entity:$('#entity').value});render()}catch(error){status(error.message,true)}};$('#clearRecord').onclick=resetForm;
$('#recordForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,spec=entitySpec(),record={id:form.id.value||undefined,site_id:form.site_id.value,status:form.status.value,[spec.label]:form.label.value.trim()};if(form.extra.value.trim())record[spec.extra]=form.extra.value.trim();if($('#entity').value==='tasks')record.priority=form.priority.value;try{await auth.rpc('admin_upsert',{entity:$('#entity').value,record});resetForm();records=await auth.rpc('admin_list',{entity:$('#entity').value});render();status('Saved and audited.')}catch(error){status(error.message,true)}});
