'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {createAdminHandler}=require('../api/_lib/handler');
const configured={SUPABASE_URL:'https://test.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'server-secret',ADMIN_JWT_AUDIENCE:'dcc-admin',ADMIN_ALLOWED_ORIGINS:'https://admin.example.test',CSRF_HMAC_SECRET:'01234567890123456789012345678901'};
function response(){return {statusCode:0,payload:null,headers:{},setHeader(k,v){this.headers[k]=v},status(n){this.statusCode=n;return this},json(v){this.payload=v;return this}}}
test('unauthenticated admin request is denied',async()=>{const old={...process.env};Object.assign(process.env,configured);try{const handler=createAdminHandler({verifyAccessToken:async()=>null,repository:{list:async()=>[]},rateLimiter:{consume:async()=>({allowed:true})}});const res=response();await handler({method:'GET',headers:{origin:'https://admin.example.test'},query:{entity:'leads'}},res);assert.equal(res.statusCode,401);assert.equal(res.payload.error.code,'authentication_required');assert.equal(res.headers['Cache-Control'],'no-store, private')}finally{process.env=old}});
test('missing server configuration fails closed without naming secrets',async()=>{const old={...process.env};for(const key of Object.keys(configured))delete process.env[key];try{const res=response();await createAdminHandler()({method:'GET',headers:{},query:{entity:'tasks'}},res);assert.equal(res.statusCode,503);assert.deepEqual(res.payload,{error:{code:'backend_not_configured',message:'Private management is not connected.'}})}finally{process.env=old}});
test('sensitive entities and secrets are excluded from public JSON',()=>{const root=path.resolve(__dirname,'..');const publicJson=['data/portfolio.json','data/portfolio.schema.json','manifest.webmanifest'];const forbidden=['contact_email','requester_email','form_submissions','claim_requests','transactions','service_role_key','csrf_hmac_secret'];for(const rel of publicJson){const value=fs.readFileSync(path.join(root,rel),'utf8').toLowerCase();for(const token of forbidden)assert.equal(value.includes(token),false,`${rel} contains ${token}`)}});
test('deployment ignore keeps private contracts, migrations and tests out of public output',()=>{const ignore=fs.readFileSync(path.resolve(__dirname,'../.vercelignore'),'utf8');for(const item of ['schemas/private/','supabase/','tests/','docs/','.env.example'])assert.match(ignore,new RegExp(item.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')))});
test('Google browser snapshot is truthful and separate from the ChatGPT snapshot',()=>{const app=fs.readFileSync(path.resolve(__dirname,'../app.js'),'utf8'),html=fs.readFileSync(path.resolve(__dirname,'../index.html'),'utf8');for(const phrase of ['Google verified browser snapshot','not a live API','Live Google API','Not connected'])assert.equal(`${app}\n${html}`.includes(phrase),true,`missing ${phrase}`);for(const phrase of ['ChatGPT Sites is a frozen analytics snapshot','Google has a dated verified browser snapshot','Only the live Google API remains not connected'])assert.match(html,new RegExp(phrase));assert.match(app,/No GSC performance is inferred for other sites/i);assert.match(app,/not GA4 or Google Search Console data/i)});
