'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..');const text=p=>fs.readFileSync(path.join(root,p),'utf8');
function response(){return {statusCode:0,payload:null,headers:{},setHeader(k,v){this.headers[k]=v},status(n){this.statusCode=n;return this},json(v){this.payload=v;return this}}}
test('public config fails closed without publishable key',()=>{const old=process.env.SUPABASE_PUBLISHABLE_KEY;delete process.env.SUPABASE_PUBLISHABLE_KEY;try{const res=response();require('../api/config')({method:'GET'},res);assert.equal(res.statusCode,503);assert.equal(res.headers['Cache-Control'],'no-store')}finally{if(old)process.env.SUPABASE_PUBLISHABLE_KEY=old}});
test('public config exposes only scoped project and publishable key',()=>{const old=process.env.SUPABASE_PUBLISHABLE_KEY;process.env.SUPABASE_PUBLISHABLE_KEY='sb_publishable_test_value';try{const res=response();require('../api/config')({method:'GET'},res);assert.equal(res.statusCode,200);assert.deepEqual(res.payload,{supabaseUrl:'https://gqbekbrxftmfpgnkqodo.supabase.co',publishableKey:'sb_publishable_test_value'});assert.equal(JSON.stringify(res.payload).includes('service'),false)}finally{if(old)process.env.SUPABASE_PUBLISHABLE_KEY=old;else delete process.env.SUPABASE_PUBLISHABLE_KEY}});
test('trusted-device session stores only scoped Supabase tokens and clears failures',()=>{const js=text('admin.js');assert.match(js,/SESSION_KEY='directory-command-centre-admin-session-v1'/);assert.match(js,/localStorage\.setItem\(SESSION_KEY,JSON\.stringify\(safe\)\)/);assert.match(js,/localStorage\.removeItem\(SESSION_KEY\)/);assert.match(js,/refresh_token/);assert.match(js,/REFRESH_LEEWAY_SECONDS=90/);assert.match(js,/visibilitychange/);for(const forbidden of ['sessionStorage','indexedDB','document.cookie'])assert.equal(js.includes(forbidden),false);for(const forbiddenField of ['email:value.email','password:value.password','service_role'])assert.equal(js.includes(forbiddenField),false)});
test('admin supports anonymous device enrolment and authorised magic-link fallback',()=>{const html=text('admin.html'),js=text('admin.js');assert.equal(html.includes('type="password"'),false);assert.match(html,/Activate this device/);assert.match(html,/Approval required/);assert.match(html,/Check approval/);assert.match(js,/\/auth\/v1\/signup/);assert.match(js,/approvalCode\(\)/);assert.match(js,/\/auth\/v1\/otp/);assert.match(js,/should_create_user:false/);assert.match(js,/email_redirect_to:exactAdminRedirect\(\)/);assert.match(js,/PRODUCTION_REDIRECT='https:\/\/directory-command-centre-pwa\.vercel\.app\/admin\.html'/)});
test('device and magic-link sessions restore, refresh, scrub redirects and remain project pinned',()=>{const js=text('admin.js');for(const token of ['access_token','refresh_token','token_hash','error_description'])assert.match(js,new RegExp(token));assert.match(js,/history\.replaceState/);assert.match(js,/claims\.iss!==`\$\{PROJECT\}\/auth\/v1`/);assert.match(js,/claims\.aud!==\'authenticated\'/);assert.match(js,/claims\.exp<=now/);assert.match(js,/\/auth\/v1\/token\?grant_type=refresh_token/);assert.match(js,/result\.response\.status===401/);assert.match(js,/\/auth\/v1\/logout\?scope=local/);assert.match(js,/credentials:'omit'/)});
test('pending device cannot bypass membership-gated RPCs and admin exposes only approved entities',()=>{const js=text('admin.js');assert.match(js,/await rpc\('admin_list',\{entity:'sites'\}\)/);assert.match(js,/isPending\(error\)/);assert.equal(js.includes('service_role'),false);const html=text('admin.html'),sql=text('supabase/migrations/0002_authenticated_admin_rpc.sql');for(const allowed of ['listings','content_items','tasks']){assert.match(html,new RegExp(allowed));assert.match(sql,new RegExp(`entity='${allowed}'`))}for(const blocked of ['leads','claim_requests','form_submissions','transactions'])assert.equal(html.includes(`value="${blocked}"`),false)});
test('migration enforces membership, audit, RLS and durable rate limits',()=>{const sql=text('supabase/migrations/0002_authenticated_admin_rpc.sql').toLowerCase();for(const phrase of ['current_admin','admin_memberships','security definer','audit_events','rate_limit_buckets','enable row level security','force row level security','grant execute'])assert.match(sql,new RegExp(phrase.replaceAll(' ','\\s+')))});
test('public RPC wrappers delegate to private functions and expose only authenticated execute',()=>{
  const sql=text('supabase/migrations/0003_public_admin_rpc_wrappers.sql').toLowerCase();
  for(const name of ['admin_list','admin_upsert','admin_delete']){
    assert.match(sql,new RegExp(`create\\s+or\\s+replace\\s+function\\s+public\\.${name}`));
    assert.match(sql,new RegExp(`security\\s+invoker[\\s\\S]+private_management\\.${name}\\(\\$1`));
    assert.match(sql,new RegExp(`revoke\\s+execute\\s+on\\s+function\\s+public\\.${name}`));
    assert.match(sql,new RegExp(`grant\\s+execute\\s+on\\s+function\\s+public\\.${name}[^;]+to\\s+authenticated`));
  }
  assert.match(sql,/from\s+public,\s*anon,\s*authenticated/);
});
test('setup documents anonymous-auth prerequisite and exact UUID approval',()=>{const docs=text('docs/PRIVATE_BACKEND_SETUP.md');assert.match(docs,/enable \*\*anonymous sign-ins\*\*/);assert.match(docs,/full UUID exactly matches/);assert.match(docs,/Never approve from the short code alone/);assert.match(docs,/should_create_user: false/)});
test('service worker never caches private admin or API responses',()=>{const sw=text('sw.js');assert.match(sw,/startsWith\('\/api\/'\)/);assert.match(sw,/endsWith\('\/admin\.html'\)/);assert.match(sw,/cache:'no-store'/)});
test('dashboard and private editor share a branded same-tab shell without merging security logic',()=>{const dashboard=text('index.html'),admin=text('admin.html');for(const html of [dashboard,admin]){assert.match(html,/Directory Command Centre/);assert.match(html,/href="\.\/#\/overview"/);assert.match(html,/href="admin\.html"/);assert.equal(html.includes('target="_blank"'),false)}assert.match(admin,/Private and gated/);assert.match(admin,/trusted-device authentication/);assert.match(text('admin.js'),/admin_list/)});
