'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..');const text=p=>fs.readFileSync(path.join(root,p),'utf8');
function response(){return {statusCode:0,payload:null,headers:{},setHeader(k,v){this.headers[k]=v},status(n){this.statusCode=n;return this},json(v){this.payload=v;return this}}}
test('public config fails closed without publishable key',()=>{const old=process.env.SUPABASE_PUBLISHABLE_KEY;delete process.env.SUPABASE_PUBLISHABLE_KEY;try{const res=response();require('../api/config')({method:'GET'},res);assert.equal(res.statusCode,503);assert.equal(res.headers['Cache-Control'],'no-store')}finally{if(old)process.env.SUPABASE_PUBLISHABLE_KEY=old}});
test('public config exposes only scoped project and publishable key',()=>{const old=process.env.SUPABASE_PUBLISHABLE_KEY;process.env.SUPABASE_PUBLISHABLE_KEY='sb_publishable_test_value';try{const res=response();require('../api/config')({method:'GET'},res);assert.equal(res.statusCode,200);assert.deepEqual(res.payload,{supabaseUrl:'https://gqbekbrxftmfpgnkqodo.supabase.co',publishableKey:'sb_publishable_test_value'});assert.equal(JSON.stringify(res.payload).includes('service'),false)}finally{if(old)process.env.SUPABASE_PUBLISHABLE_KEY=old;else delete process.env.SUPABASE_PUBLISHABLE_KEY}});
test('admin session is memory-only and never persisted',()=>{const js=text('admin.js');assert.match(js,/let config=null,session=null/);assert.match(js,/addEventListener\('pagehide',\(\)=>\{session=null\}\)/);for(const forbidden of ['localStorage','sessionStorage','indexedDB','document.cookie'])assert.equal(js.includes(forbidden),false)});
test('admin uses passwordless magic links without creating users',()=>{const html=text('admin.html'),js=text('admin.js');assert.equal(html.includes('type="password"'),false);assert.match(html,/Email sign-in link/);assert.match(js,/\/auth\/v1\/otp/);assert.match(js,/should_create_user:false/);assert.match(js,/email_redirect_to:sameOriginAdminUrl\(\)/);assert.match(js,/\/admin\.html/)});
test('magic-link redirect is scrubbed and pinned before use',()=>{const js=text('admin.js');for(const token of ['access_token','refresh_token','token_hash','error_description'])assert.match(js,new RegExp(token));assert.match(js,/history\.replaceState/);assert.match(js,/claims\.iss!==`\$\{PROJECT\}\/auth\/v1`/);assert.match(js,/claims\.aud!==\'authenticated\'/);assert.match(js,/credentials:\'omit\'/)});
test('admin exposes only approved first-phase entities',()=>{const html=text('admin.html'),sql=text('supabase/migrations/0002_authenticated_admin_rpc.sql');for(const allowed of ['listings','content_items','tasks']){assert.match(html,new RegExp(allowed));assert.match(sql,new RegExp(`entity='${allowed}'`))}for(const blocked of ['leads','claim_requests','form_submissions','transactions'])assert.equal(html.includes(`value="${blocked}"`),false)});
test('migration enforces membership, audit, RLS and durable rate limits',()=>{const sql=text('supabase/migrations/0002_authenticated_admin_rpc.sql').toLowerCase();for(const phrase of ['current_admin','admin_memberships','security definer','audit_events','rate_limit_buckets','enable row level security','force row level security','grant execute'])assert.match(sql,new RegExp(phrase.replaceAll(' ','\\s+')))});
test('service worker never caches private admin or API responses',()=>{const sw=text('sw.js');assert.match(sw,/startsWith\('\/api\/'\)/);assert.match(sw,/endsWith\('\/admin\.html'\)/);assert.match(sw,/cache:'no-store'/)});
